<?php

/**
 * @file
 * Defines a field for storing entity_type/bunlde pairs.
 */

/**
 * Implements hook_field_info().
 */
function entity_type_bundle_field_field_info() {
  return [
    'entity_type_bundle' => [
      'label' => t('Entity type and bundle'),
      'description' => t('Stores a pair of entity type/bundle.'),
      'settings' => [],
      'instance_settings' => [],
      'default_widget' => 'entity_type_bundle',
      'default_formatter' => 'entity_type_bundle',
      'property_type' => 'entity_type_bundle',
      'property_callbacks' => ['entity_type_bundle_property_info_callback'],
    ],
  ];
}

/**
 * Implements hook_field_presave().
 */
function entity_type_bundle_field_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'entity_type_bundle') {
    foreach ($items as $delta => $item) {
      // If the widget used is entity_type_bundle, it will only set one property
      // (entity_type_bundle), in the format "entity_type|bundle". We need to
      // split it and set the correct properties for storing.
      if (isset($item['entity_type_bundle'])) {
        list($items[$delta]['entity_type'], $items[$delta]['bundle']) = explode('|', $item['entity_type_bundle']);
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function entity_type_bundle_field_field_is_empty($item, $field) {
  // The field is empty if the sored columns are empty, and the pseudocolumn
  // used by the 'entity_type_bundle' widget is also empty, or contains the
  // empty value.
  if ((empty($item['entity_type']) && empty($item['bundle'])) &&
      (empty($item['entity_type_bundle']) || $item['entity_type_bundle'] == '_none')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_formatter_info().
 */
function entity_type_bundle_field_field_formatter_info() {
  return [
    'entity_type_bundle' => [
      'label' => t('Default'),
      'field types' => ['entity_type_bundle'],
    ],
  ];
}

/**
 * Implements hook_field_formatter_view().
 */
function entity_type_bundle_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = [];
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'entity_type_bundle':
      foreach ($items as $delta => $item) {
        $element[$delta]['entity_type'] = ['#markup' => t('Entity type') . ': ' . $item['entity_type']];
        $element[$delta]['bundle'] = ['#markup' => t('Bundle') . ': ' . $item['bundle']];
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function entity_type_bundle_field_field_widget_info() {
    return [
      'entity_type_bundle' => [
        'label' => t('Entity type and bundle selector'),
        'field types' => ['entity_type_bundle'],
      ],
    ];
}

/**
 * Implements hook_field_widget_form().
 */
function entity_type_bundle_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $required = $element['#required'];
  // Filter the options to show only the bundles for commerce_product.
  // Required for field_product_family.
  if($element['#field_name'] == 'field_product_family' && in_array($element['#entity']->type,['advisers','selection_criteria'])) {
    $element += [
      '#type' => 'select',
      '#options' => _entity_type_bundle_product_types_options_list($required),
      '#default_value' => isset($items[$delta]) ? $items[$delta]['entity_type'] . '|' . $items[$delta]['bundle'] : '_none',
    ];
  }
  else {
    $element += [
      '#type' => 'select',
      '#options' => _entity_type_bundle_options_list($required),
      '#default_value' => isset($items[$delta]) ? $items[$delta]['entity_type'] . '|' . $items[$delta]['bundle'] : '_none',
    ];
  }
  return ['entity_type_bundle' => $element];
}

/**
 * Generate the list of possible entity_types and bundles.
 *
 * @param boolean $required
 * @return array
 */
function _entity_type_bundle_options_list($required) {
  $entities_info = entity_get_info();
  $options = [];

  // If the field is not required, add an option for empty value.
  if (!$required) {
    $options['_none'] = t('- Select a value -');
  }

  // Create one option per entity_type/bundle pair, and group them by entity
  // type.
  foreach($entities_info as $entity_type => $entity_info) {
    $options_subset = [];
    foreach ($entity_info['bundles'] as $bundle => $bundle_info) {
      $key = $entity_type . '|' . $bundle;
      $options_subset[$key] = $bundle_info['label'];
    }
    $options[$entity_info['label']] = $options_subset;
  }

  return $options;
}

/**
 * Generate the list of possible bundles for a specific entity_type.
 *
 * @param boolean $required
 * @return array
 */
function _entity_type_bundle_product_types_options_list($required) {
  $entities_info = entity_get_info();
  $options = [];
  $entity_type = 'commerce_product';

  // If the field is not required, add an option for empty value.
  if (!$required) {
    $options['_none'] = t('- Select a value -');
  }

  // Create one option per entity_type/bundle pair.
  if(isset($entities_info[$entity_type])){
    $entity_info = $entities_info[$entity_type];
    foreach ($entity_info['bundles'] as $bundle => $bundle_info) {
      $key = $entity_type . '|' . $bundle;
      $options[$key] = $bundle_info['label'];
    }
  }

  return $options;
}

/**
 * Callback to alter the property info of entity_type/bundle fields.
 *
 * @see entity_type_bundle_field_field_info().
 */
function entity_type_bundle_property_info_callback(&$info, $entity_type, $field, $instance, $field_type) {
  $name = $field['field_name'];
  $property = &$info[$entity_type]['bundles'][$instance['bundle']]['properties'][$name];

  $property['type'] = ($field['cardinality'] != 1) ? 'list<entity_type_bundle>' : 'entity_type_bundle';
  $property['getter callback'] = 'entity_metadata_field_verbatim_get';
  $property['setter callback'] = 'entity_metadata_field_verbatim_set';
  $property['auto creation'] = 'entity_type_bundle_field_data_auto_creation';
  $property['property info'] = entity_type_bundle_field_data_property_info();

  unset($property['query callback']);
}

/**
 * Returns the default array structure for an entity_ytpe/bundle field for use
 * when creating new data arrays through an entity metadata wrapper.
 */
function entity_type_bundle_field_data_auto_creation() {
  return ['entity_type' => NULL, 'bundle' => NULL];
}

/**
 * Defines info for the properties of the entity_ytpe/bundle field data
 * structure.
 */
function entity_type_bundle_field_data_property_info($name = NULL) {
  return [
    'entity_type' => [
      'label' => t('Entity type'),
      'description' => !empty($name) ? t('Entity type referenced by field %name', ['%name' => $name]) : '',
      'type' => 'text',
      'getter callback' => 'entity_property_verbatim_get',
      'setter callback' => 'entity_property_verbatim_set',
    ],
    'bundle' => [
      'label' => t('Bundle'),
      'description' => !empty($name) ? t('Bundle referenced by field %name', ['%name' => $name]) : '',
      'type' => 'text',
      'getter callback' => 'entity_property_verbatim_get',
      'setter callback' => 'entity_property_verbatim_set',
      'options list' => 'entity_type_bundle_unit_options',
    ],
  ];
}
